{{- if .Values.ingress.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.ingress.useTls }}
    kubernetes.io/tls-acme: "true"
{{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
{{- if .Values.ingress.paths }}
{{ toYaml .Values.ingress.paths | indent 6 }}
{{- end }}
      - path: /
        {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
        backend:
          serviceName: {{ template "name" . }}
          servicePort: {{ .Values.service.externalPort }}
        {{- else }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "name" . }}
            port:
              number: {{ .Values.service.externalPort }}
        {{- end }}
{{- if .Values.ingress.useTls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ template "name" . }}-tls-secret
{{- end -}}
{{- end -}}
