{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.ingress.useTls }}
    kubernetes.io/tls-acme: "true"
{{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
{{- if .Values.ingress.paths }}
{{ toYaml .Values.ingress.paths | indent 6 }}
{{- end }}
{{- if .Values.ingress.useTls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ template "name" . }}-tls-secret
{{- end -}}
{{- end -}}
