stages:
  - prepare
  - build
  - deploy

default:
  tags:
    - kubernetes-runner

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

package-charts:
  stage: prepare
  image:
    name: alpine/helm
    entrypoint: [""]
  script:
    - apk add --no-cache bash
    - ./package-charts.sh
  artifacts:
    paths:
      - dist/
    expire_in: 1 weeks

build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    # rename dist folder from restored artifact
    - mv ./dist ./dist-artifact
    # get "old" dist folder from latest image
    - docker run -v $PWD/dist:/output --entrypoint /bin/sh $CI_REGISTRY_IMAGE:latest -c "rm -rf /output/* && cp -r /usr/share/nginx/html/* /output"
    # copy dist artifact into "old" dist that contains previous packaged charts
    - cp -r ./dist-artifact/* ./dist
    # generate chart readme files
    - docker run --rm --volume "$PWD/charts:/helm-docs" -u $(id -u) jnorwood/helm-docs:latest
    - docker build -f docker/Dockerfile --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# https://docs.gitlab.com/ee/user/project/clusters/#deploying-to-a-kubernetes-cluster
deploy:
  stage: deploy
  image:
    name: alpine/helm
    entrypoint: [""]
  environment:
    name: dev # matches environment scope of cluster defined at https://gitlab.com/mhub1/platform/helm-charts/-/clusters
    kubernetes: # needed for cluster access
  variables:
    NAMESPACE: helm-repository
    HELM_RELEASE: helm-repository
  script:
    - ./deployment/deploy.sh $NAMESPACE $HELM_RELEASE
  only:
    - master
